name: "Run Orders Service Tests"

on:
  pull_request:
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd orders && npm i && npm run test:ci
