name: Run Auth Service Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd auth && npm install
      - run: npm run test:ci
